// <auto-generated />
namespace _1911066045_ThaiHuuDang_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Attendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Attendance));
        
        string IMigrationMetadata.Id
        {
            get { return "202203271103261_Attendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
